# Generated by Django 6.1 on 2026-08-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_login', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigiLockerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(default='arogya_user_1', max_length=255)),
                ('uri', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
