# Generated by Django 6.1 on 2026-09-16 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_login', '0008_alter_otp_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_phone', models.CharField(max_length=15)),
                ('uploaded_image', models.ImageField(upload_to='prescriptions/%Y/%m/%d/')),
                ('raw_gemini_response', models.TextField(blank=True, default='')),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, default='', max_length=200)),
                ('dosage', models.CharField(blank=True, default='', max_length=100)),
                ('frequency', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('instructions', models.TextField(blank=True, default='')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='otp_login.prescriptiondraft')),
            ],
        ),
    ]
