# Generated by Django 6.1 on 2026-09-16 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_login', '0009_prescriptiondraft_prescriptionmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalIntakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_phone', models.CharField(max_length=15)),
                ('symptoms', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=150)),
                ('severity', models.CharField(blank=True, max_length=100)),
                ('doctor_suggestion', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('unanswered_questions', models.JSONField(blank=True, default=list)),
                ('merged_record', models.JSONField(blank=True, default=dict)),
                ('patient_summary', models.TextField(blank=True)),
                ('hip_status', models.CharField(choices=[('NOT_SENT', 'Not sent'), ('SENT', 'Sent to HIP')], default='NOT_SENT', max_length=30)),
                ('hip_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otp_login.prescriptiondraft')),
            ],
        ),
    ]
