# Generated by Django 6.1.1 on 2026-09-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_login', '0010_clinicalintakesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORSBedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_location', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('bed_type', models.CharField(max_length=100)),
                ('admission_reason', models.TextField(blank=True, default='')),
                ('preferred_admission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Request Submitted'), ('CONFIRMED', 'Bed Confirmed'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20)),
                ('ors_reference', models.CharField(max_length=100, unique=True)),
                ('estimated_wait', models.CharField(blank=True, default='', max_length=100)),
                ('assigned_bed_label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ors_bed_requests', to='otp_login.userprofile')),
            ],
        ),
    ]
